// ======= Styles Barrel File =======
// Re-exports all style management functions

export {
	THEME_COLOR,
	THEME_COLOR_HOVER,
	THEME_COLOR_SECONDARY,
	THEME_COLOR_SECONDARY_HOVER,
	LIGHT_COLOR,
	DARK_COLOR,
	BOX_COLOR,
	loadLogoColors,
	loadThemeColors,
	getLocalColors,
	getEquivalentColorAndPosition,
	getLighterColor,
	getDarkerColor,
	getColorIndexFromOptions,
	getMixedColor,
	getSecondaryColor,
	getColorNameFromOptions,
	getColorHexFromOptions,
	getThemeColorBoxShadow,
	changeFillColorSVGs,
	clearCustomColors,
	changeBarColorIOS,
	saveLocalColors,
	setThemeColor,
	setThemeColorHover,
	setThemeColorSecondary,
	setThemeColorSecondaryHover,
	setLightColor,
	setDarkColor,
	hexToRgb,
	rgbToHex,
	rgbToText,
	hexToRgbText,
} from '../theme/colors.js';

export {
	CHANGED_SVGS,
	LOGO_LIGHT,
	LOGO_DARK,
	loadVisibility,
	loadDarkMode,
	loadLightMode,
	loadLightModeLite,
	applyThemeAttribute,
	loadUserVisibility,
	applyMode,
	switchVisibility,
	autoVisibility,
	disableScroll,
	enableScroll,
	hasCSSRule,
	isOnDarkMode,
	openModal,
	closeModal,
	isModalOpen,
	loadEditModule,
	loadListener,
	showContent,
	hideContent,
	addRemoveChildListener,
	toggleFadingVisibility,
	searchDestinationsListenerAction,
	visibilityAdd,
	getVisibility,
	loadExternalVisibility,
} from '../theme/visibility.js';

export {
	animate,
	animateRight,
	animateLeft,
	animateUp,
	animateDown,
	fadeOut,
	fadeIn,
	fade,
	swipeOut,
	swipeIn,
	getSwipeDirection,
	swipe,
} from '../theme/animations.js';

export {
	setCSSRule,
	removeCSSRule,
	setCSSRuleBatch,
	removeCSSRuleBatch,
	setCSSMediaRule,
	removeCSSMediaRule,
	setCSSMediaRuleBatch,
	removeCSSMediaRuleBatch,
	setCSSVariable,
	removeCSSVariable,
} from '../theme/stylesheets.js';
